# Generated by Django 5.2.6 on 2025-10-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrusel',
            options={},
        ),
        migrations.AlterField(
            model_name='carrusel',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
    ]
