# Generated by Django 5.2.6 on 2025-10-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrousel', '0002_alter_carrusel_options_alter_carrusel_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrusel',
            name='link',
            field=models.URLField(blank=True, help_text='URL opcional a la que apuntará la imagen del carrusel', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='carrusel',
            name='estado',
            field=models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=10),
        ),
    ]
