# Generated by Django 5.2.6 on 2025-09-17 06:53
# Migración inicial para la app 'productos'.
# Crea las tablas 'Categoria' y 'Producto' en la base de datos.
# Fue generada automáticamente por Django 5.2.6 el 17 de septiembre de 2025.

import django.db.models.deletion
# Importa el tipo de eliminación que se usará en claves foráneas (ej. CASCADE).

from django.db import migrations, models
# Importa las clases necesarias para definir operaciones de migración y tipos de campos.


class Migration(migrations.Migration):

    initial = True
    # Indica que esta es la primera migración de la app. Crea las tablas desde cero.

    dependencies = [
    ]
    # No depende de ninguna otra migración previa. Es la base inicial.

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Campo ID autogenerado como clave primaria.

                ('nombre', models.CharField(max_length=100, unique=True)),
                # Campo de texto para el nombre de la categoría. Debe ser único.

                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                # Campo para subir una imagen. Se guarda en 'media/categorias/'.

                ('descripcion', models.TextField(blank=True)),
                # Campo de texto largo para la descripción. Opcional.

                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                # Campo para indicar si la categoría está activa o inactiva.
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Campo ID autogenerado como clave primaria.

                ('nombre', models.CharField(max_length=150)),
                # Nombre del producto.

                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                # Imagen del producto. Se guarda en 'media/productos/'.

                ('descripcion', models.TextField(blank=True)),
                # Descripción del producto. Opcional.

                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                # Precio con dos decimales. Máximo 99999999.99.

                ('stock', models.PositiveIntegerField()),
                # Cantidad disponible. Solo acepta valores positivos.

                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                # Estado del producto: activo o inactivo.

                ('ingredientes', models.TextField(blank=True)),
                # Lista de ingredientes. Opcional.

                ('instrucciones_conservacion', models.TextField(blank=True)),
                # Indicaciones para conservar el producto. Opcional.

                ('instrucciones_uso', models.TextField(blank=True)),
                # Indicaciones para usar o preparar el producto. Opcional.

                ('categoria', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='productos',
                    to='productos.categoria')),
                # Relación con la categoría. Si se elimina la categoría, se eliminan sus productos.
                # 'related_name' permite acceder a los productos desde una categoría: categoria.productos.all()
            ],
        ),
    ]

# ¿Qué hace esta migracion?

    # Crea las tablas productos_categoria y productos_producto en la base de datos.

    # Define los campos, tipos de datos, relaciones y restricciones.

    # Es el paso que traduce tu código Python en estructuras reales dentro de PostgreSQL.