# Generated by Django 5.2.6 on 2025-09-17 05:09
# Migración generada por Django 5.2.6 el 17 de septiembre de 2025 a las 05:09.
# Esta migración modifica el campo 'email' del modelo 'Usuario' para asegurar que sea único.

from django.db import migrations, models
# Importa las clases necesarias para definir operaciones de migración y tipos de campos.


class Migration(migrations.Migration):
    # Define la clase que representa esta migración.

    dependencies = [
        ('users', '0001_initial'),
    ]
    # Esta migración depende de la migración inicial de la app 'users'.
    # Se ejecuta después de que se haya creado el modelo 'Usuario'.

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        # Modifica el campo 'email' del modelo 'Usuario':
        # - Establece que el email debe ser único en la base de datos.
        # - Esto evita que dos usuarios puedan registrarse con el mismo correo.
        # - max_length=254 es el valor estándar para correos electrónicos.
    ]
